function obj = readSetupSheet(obj, filename)

    arguments (Input)
        obj (1,1) setup.Setup
        filename (1,1) string
    end

    data = readcell(filename);

    %Info
    obj.Info = setup.Info( ...
        Engineer = data{5,2}, ...
        Mechanic=data{6,2}, ...
        IssueNo=data{5,11}, ...
        DateIssued=data{5,16});

    %Driver
    obj.Driver = setup.Driver( ...
        DriverName=data{9,3}, ...
        DriverWeight=data{9,5});

    %Race information
    obj.RaceInfo = setup.RaceInformation( ...
        Circuit=data{8,10}, ...
        LapDist=data{9,10}); 

    %Tyres and Chassis
    obj.Tyres=data{8,16};%come back change after do tyres class
    obj.Chassis=data{9,16};

    %Differential
    obj.Differential = setup.Differential( ...
        Diff=data{11,3}, ...
        Ramps=data{12,3},... 
        PreLoad=data{13,3});

    %Brakes
    obj.Brakes=setup.Brakes( ...
        FrontMC=data{12,9}, ...
        RearMC=data{12,11}, ...
        FrontPads=data{13,9}, ...
        RearPads=data{13,11});

    %ACCU,Cooling,Rack
    obj.AccuConfig=data{11,16};
    obj.Cooling=data{12,16};
    obj.SteeringRack=data{13,16};

    %Gear Ratios
    obj.GearRatios=setup.GearRatios(...
        FrontSprocketToothCount=data{15,4}, ...
        RearSprocketToothCount=data{15,5}, ...
        FDR=data{15,6});

    %Aero
    obj.Aero=setup.Aero( ...
        FrontWing=data{18,8}, ...
        SideWing=data{18,10}, ...
        RearWing=data{18,12});

    %Tires

    %Front Left
    obj.Tires(1)=setup.TireSetup(ToeAngle=data{22,3}, ...
    ToeMMSHM=data{22,5}, ...
    CamberAngle=data{23,3}, ...
    CamberMMSHM=data{23,5}, ...
    HardpointUF=[data{25,3},data{26,3}], ...
    HardpointUR=[data{25,4},data{26,3}], ...
    HardpointLF=[data{25,5},data{26,5}], ...
    HardpointLR=[data{25,6},data{26,5}], ... 
    RideHeightAngle=data{27,3}, ...
    RideHeightMMSHM=data{27,5}, ...
    TempID=data{29,3}, ...
    TempCold=data{29,4}, ...
    TempHot=data{29,5}, ...
    Temperature=data{29,6}, ...
    CornerWeight=data{29,6});

    %Front Right

    obj.Tires(2)=setup.TireSetup(ToeAngle=data{22,16}, ...
        ToeMMSHM=data{22,18}, ...
        CamberAngle=data{23,16}, ...
        CamberMMSHM=data{23,18}, ...
        HardpointUF=[data{25,16},data{26,16}], ...
        HardpointUR=[data{25,17},data{26,16}], ...
        HardpointLF=[data{25,18},data{26,18}], ...
        HardpointLR=[data{25,19},data{26,18}], ... 
        RideHeightAngle=data{27,16}, ...
        RideHeightMMSHM=data{27,18}, ...
        TempID=data{29,16}, ...
        TempCold=data{29,17}, ...
        TempHot=data{29,18}, ...
        Temperature=data{29,19}, ...
        CornerWeight=data{30,16});

    %Rear Left
    obj.Tires(3)=setup.TireSetup(ToeAngle=data{40,3}, ...
        ToeMMSHM=data{40,5}, ...
        CamberAngle=data{41,3}, ...
        CamberMMSHM=data{41,5}, ...
        HardpointUF=[data{43,3},data{44,3}], ...
        HardpointUR=[data{43,4},data{44,3}], ...
        HardpointLF=[data{43,5},data{44,3}], ...
        HardpointLR=[data{43,6},data{44,3}], ... 
        RideHeightAngle=data{45,3}, ...
        RideHeightMMSHM=data{45,5}, ...
        TempID=data{47,3}, ...
        TempCold=data{47,4}, ...
        TempHot=data{47,5}, ...
        Temperature=data{47,6}, ...
        CornerWeight=data{48,3});

    %Rear Right
    obj.Tires(4)=setup.TireSetup(ToeAngle=data{40,16}, ...
        ToeMMSHM=data{40,18}, ...
        CamberAngle=data{41,16}, ...
        CamberMMSHM=data{41,18}, ...
        HardpointUF=[data{43,16},data{44,16}], ...
        HardpointUR=[data{43,17},data{44,16}], ...
        HardpointLF=[data{43,18},data{44,16}], ...
        HardpointLR=[data{43,19},data{44,16}], ... 
        RideHeightAngle=data{45,16}, ...
        RideHeightMMSHM=data{45,18}, ...
        TempID=data{47,16}, ...
        TempCold=data{47,17}, ...
        TempHot=data{47,18}, ...
        Temperature=data{47,19}, ...
        CornerWeight=data{48,16});

    %Suspension

    %Front

    %Heave
    obj.Suspension(1)=setup.Suspension(Spring=data{22,9}, ...
        OpenLSC=data{24,9}, OpenLSR=data{24,10}, ...
        OpenHSC=data{24,11}, OpenHSR=data{24,12});

    %Roll
    obj.Suspension(2)=setup.Suspension(Spring=data{28,9}, ...
        OpenLSC=data{30,9}, OpenLSR=data{30,10}, ...
        OpenHSC=data{30,11}, OpenHSR=data{30,12});

    %Rear

    %Heave
    obj.Suspension(3)=setup.Suspension(Spring=data{40,9}, ...
        OpenLSC=data{42,9}, OpenLSR=data{42,10}, ...
        OpenHSC=data{42,11}, OpenHSR=data{42,12});

    %Roll
    obj.Suspension(4)=setup.Suspension(Spring=data{46,9}, ...
        OpenLSC=data{48,9}, OpenLSR=data{48,10}, ...
        OpenHSC=data{48,11}, OpenHSR=data{48,12});


    %WeightDistribution
    obj.WeightDistribution=setup.WeightDistribution(Weight=data{33,3}, ...
        Gravity=data{34,3}, XWeightPercentage=data{34,5}, ...
        FWD=data{35,3}, LWD=data{36,3});

    %ChassisBalance
    obj.Chassisbalance=setup.Chassisbalance(MINRH=data{33,16}, ...
    Rake=data{35,16}, LWD=data{36,16});