USMSetupSheet=readcell("24SetupSheet.xlsx");

setup=struct();

%Info
setup.Info = Info( ...
    Engineer = USMSetupSheet{5,2}, ...
    Mechanic=USMSetupSheet{6,2}, ...
    IssueNo=USMSetupSheet{5,11}, ...
    DateIssued=USMSetupSheet{5,16});

%Driver
setup.Driver=Driver( ...
    DriverName=USMSetupSheet{9,3}, ...
    DriverWeight=USMSetupSheet{9,5});

%Race information
setup.RaceInfo=RaceInformation( ...
    Circuit=USMSetupSheet{8,10}, ...
    LapDist=USMSetupSheet{9,10}); 

%Tyres and Chassis
setup.Tyres1=USMSetupSheet{8,16};%come back change after do tyres class
setup.Chassis=USMSetupSheet{9,16};

%Differential
setup.Differential = Differential( ...
    Diff=USMSetupSheet{11,3}, ...
    Ramps=USMSetupSheet{12,3},... 
    PreLoad=USMSetupSheet{13,3});

%Brakes
setup.Brakes=Brakes( ...
    FrontMC=USMSetupSheet{12,9}, ...
    RearMC=USMSetupSheet{12,11}, ...
    FrontPads=USMSetupSheet{13,9}, ...
    RearPads=USMSetupSheet{13,11});

%ACCU,Cooling,Rack
setup.ACCUconfig=USMSetupSheet{11,16};
setup.Cooling=USMSetupSheet{12,16};
setup.Rack=USMSetupSheet{13,16};

%Gear Ratios
setup.GearRatios=GearRatios(...
    FrontSprocketToothCount=USMSetupSheet{15,4}, ...
    RearSprocketToothCount=USMSetupSheet{15,5}, ...
    FDR=USMSetupSheet{15,6});

%Aero
setup.Aero=Aero( ...
    FrontWing=USMSetupSheet{18,8}, ...
    SideWing=USMSetupSheet{18,10}, ...
    RearWing=USMSetupSheet{18,12});

%Tires

%Front Left
setup.Tires.FrontLeft=TireSetup(ToeAngle=USMSetupSheet{22,3}, ...
   ToeMMSHM=USMSetupSheet{22,5}, ...
   CamberAngle=USMSetupSheet{23,3}, ...
   CamberMMSHM=USMSetupSheet{23,5}, ...
   HardpointUF=[USMSetupSheet{25,3},USMSetupSheet{26,3}], ...
   HardpointUR=[USMSetupSheet{25,4},USMSetupSheet{26,3}], ...
   HardpointLF=[USMSetupSheet{25,5},USMSetupSheet{26,5}], ...
   HardpointLR=[USMSetupSheet{25,6},USMSetupSheet{26,5}], ... 
   RideHeightAngle=USMSetupSheet{27,3}, ...
   RideHeightMMSHM=USMSetupSheet{27,5}, ...
   TempID=USMSetupSheet{29,3}, ...
   TempCold=USMSetupSheet{29,4}, ...
   TempHot=USMSetupSheet{29,5}, ...
   Temperature=USMSetupSheet{29,6}, ...
   CornerWeight=USMSetupSheet{29,6});

%Front Right

setup.Tires.FrontRight=TireSetup(ToeAngle=USMSetupSheet{22,16}, ...
    ToeMMSHM=USMSetupSheet{22,18}, ...
    CamberAngle=USMSetupSheet{23,16}, ...
    CamberMMSHM=USMSetupSheet{23,18}, ...
    HardpointUF=[USMSetupSheet{25,16},USMSetupSheet{26,16}], ...
    HardpointUR=[USMSetupSheet{25,17},USMSetupSheet{26,16}], ...
    HardpointLF=[USMSetupSheet{25,18},USMSetupSheet{26,18}], ...
    HardpointLR=[USMSetupSheet{25,19},USMSetupSheet{26,18}], ... 
    RideHeightAngle=USMSetupSheet{27,16}, ...
    RideHeightMMSHM=USMSetupSheet{27,18}, ...
    TempID=USMSetupSheet{29,16}, ...
    TempCold=USMSetupSheet{29,17}, ...
    TempHot=USMSetupSheet{29,18}, ...
    Temperature=USMSetupSheet{29,19}, ...
    CornerWeight=USMSetupSheet{30,16});

%Rear Left
setup.Tires.RearLeft=TireSetup(ToeAngle=USMSetupSheet{40,3}, ...
    ToeMMSHM=USMSetupSheet{40,5}, ...
    CamberAngle=USMSetupSheet{41,3}, ...
    CamberMMSHM=USMSetupSheet{41,5}, ...
    HardpointUF=[USMSetupSheet{43,3},USMSetupSheet{44,3}], ...
    HardpointUR=[USMSetupSheet{43,4},USMSetupSheet{44,3}], ...
    HardpointLF=[USMSetupSheet{43,5},USMSetupSheet{44,3}], ...
    HardpointLR=[USMSetupSheet{43,6},USMSetupSheet{44,3}], ... 
    RideHeightAngle=USMSetupSheet{45,3}, ...
    RideHeightMMSHM=USMSetupSheet{45,5}, ...
    TempID=USMSetupSheet{47,3}, ...
    TempCold=USMSetupSheet{47,4}, ...
    TempHot=USMSetupSheet{47,5}, ...
    Temperature=USMSetupSheet{47,6}, ...
    CornerWeight=USMSetupSheet{48,3});

%Rear Right
setup.Tires.RearRight=TireSetup(ToeAngle=USMSetupSheet{40,16}, ...
    ToeMMSHM=USMSetupSheet{40,18}, ...
    CamberAngle=USMSetupSheet{41,16}, ...
    CamberMMSHM=USMSetupSheet{41,18}, ...
    HardpointUF=[USMSetupSheet{43,16},USMSetupSheet{44,16}], ...
    HardpointUR=[USMSetupSheet{43,17},USMSetupSheet{44,16}], ...
    HardpointLF=[USMSetupSheet{43,18},USMSetupSheet{44,16}], ...
    HardpointLR=[USMSetupSheet{43,19},USMSetupSheet{44,16}], ... 
    RideHeightAngle=USMSetupSheet{45,16}, ...
    RideHeightMMSHM=USMSetupSheet{45,18}, ...
    TempID=USMSetupSheet{47,16}, ...
    TempCold=USMSetupSheet{47,17}, ...
    TempHot=USMSetupSheet{47,18}, ...
    Temperature=USMSetupSheet{47,19}, ...
    CornerWeight=USMSetupSheet{48,16});

%Suspension

%Front

%Heave
setup.FrontSuspension.Heave=Suspension(Spring=USMSetupSheet{22,9}, ...
    OpenLSC=USMSetupSheet{24,9}, OpenLSR=USMSetupSheet{24,10}, ...
    OpenHSC=USMSetupSheet{24,11}, OpenHSR=USMSetupSheet{24,12});

%Roll
setup.FrontSuspension.Roll=Suspension(Spring=USMSetupSheet{28,9}, ...
    OpenLSC=USMSetupSheet{30,9}, OpenLSR=USMSetupSheet{30,10}, ...
    OpenHSC=USMSetupSheet{30,11}, OpenHSR=USMSetupSheet{30,12});

%Rear

%Heave
setup.RearSuspension.Heave=Suspension(Spring=USMSetupSheet{40,9}, ...
    OpenLSC=USMSetupSheet{42,9}, OpenLSR=USMSetupSheet{42,10}, ...
    OpenHSC=USMSetupSheet{42,11}, OpenHSR=USMSetupSheet{42,12});

%Roll
setup.RearSuspension.Roll=Suspension(Spring=USMSetupSheet{46,9}, ...
    OpenLSC=USMSetupSheet{48,9}, OpenLSR=USMSetupSheet{48,10}, ...
    OpenHSC=USMSetupSheet{48,11}, OpenHSR=USMSetupSheet{48,12});


%WeightDistribution
setup.WeightDistribution=WeightDistribution(Weight=USMSetupSheet{33,3}, ...
    Gravity=USMSetupSheet{34,3}, XWeightPercentage=USMSetupSheet{34,5}, ...
    FWD=USMSetupSheet{35,3}, LWD=USMSetupSheet{36,3});

%ChassisBalance
setup.ChassisBalance=Chassisbalance(MINRH=USMSetupSheet{33,16}, ...
    Rake=USMSetupSheet{35,16}, LWD=USMSetupSheet{36,16});

%write to excel not correct but runs
writetable(struct2table(setup), 'Setup.xlsx')
